### ISSUE TITLE
抽选信息上报了错误的数据

### ISSUE THREAD

**Issue by jim-kirisame** [AtmoOmen/HousingChecker#1]
1. 没有提取中签信息，导致上报后原有信息被覆盖。请参考 [https://github.com/Lotlab/HousingCheckXP/blob/master/HousingCheck/HousingLotteryInfo.cs](HousingLotteryInfo.cs) 添加中签信息。
2. 抽选信息会上报两次 [https://github.com/AtmoOmen/HousingChecker/blob/dc432ec69d7cbda3117468549fdc248919b965f8/HousingChecker/Managers/HousingStatsManager.cs#L132](HousingStatsManager.cs#L132) 和L129 添加了相同的信息。

**Comment by AtmoOmen** [comment]
应该已经修复了 感谢指出
